create extension if not exists pgcrypto;

create type public.content_status as enum ('draft','pending','verified','rejected','needs_review','published','archived');
create type public.question_type as enum ('single_correct_mcq','multiple_correct_mcq','numerical','true_false','assertion_reason','match_following','passage');

create table public.exam_categories (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, created_at timestamptz not null default now());
create table public.exams (id uuid primary key default gen_random_uuid(), category_id uuid references public.exam_categories(id), slug text unique not null, name text not null, short_name text not null, status text not null default 'draft', default_language text not null default 'en', supported_languages text[] not null default array['en'], created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.exam_patterns (id uuid primary key default gen_random_uuid(), exam_id uuid not null references public.exams(id) on delete cascade, version text not null, duration_minutes integer not null check (duration_minutes > 0), total_questions integer not null check (total_questions > 0), maximum_marks numeric not null, marks_correct numeric not null, marks_incorrect numeric not null default 0, marks_unanswered numeric not null default 0, source_url text, effective_from date, configuration jsonb not null default '{}', unique(exam_id,version));
create table public.subjects (id uuid primary key default gen_random_uuid(), exam_id uuid not null references public.exams(id) on delete cascade, slug text not null, name text not null, display_order integer not null default 0, metadata jsonb not null default '{}', unique(exam_id,slug));
create table public.chapters (id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(id) on delete cascade, slug text not null, name text not null, display_order integer not null default 0, syllabus_version text, source_url text, status public.content_status not null default 'draft', unique(subject_id,slug));
create table public.topics (id uuid primary key default gen_random_uuid(), chapter_id uuid not null references public.chapters(id) on delete cascade, parent_topic_id uuid references public.topics(id), slug text not null, name text not null, display_order integer not null default 0, status public.content_status not null default 'draft', unique(chapter_id,slug));

create table public.questions (id uuid primary key default gen_random_uuid(), exam_id uuid not null references public.exams(id), subject_id uuid not null references public.subjects(id), chapter_id uuid references public.chapters(id), topic_id uuid references public.topics(id), question_text text not null, question_type public.question_type not null default 'single_correct_mcq', difficulty text check (difficulty in ('easy','medium','hard')), year integer check (year between 1900 and 2200), is_pyq boolean not null default false, is_ai_generated boolean not null default false, source text, source_url text, answer_key_source text, language text not null default 'en', explanation text, image_url text, diagram_url text, verification_status public.content_status not null default 'pending', explanation_status public.content_status not null default 'pending', license_metadata jsonb not null default '{}', content_hash text not null, created_by uuid references auth.users(id), verified_by uuid references auth.users(id), verified_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(exam_id,content_hash));
create table public.question_options (id uuid primary key default gen_random_uuid(), question_id uuid not null references public.questions(id) on delete cascade, option_key text not null, option_text text not null, image_url text, is_correct boolean not null default false, display_order integer not null, unique(question_id,option_key));
create table public.question_translations (id uuid primary key default gen_random_uuid(), question_id uuid not null references public.questions(id) on delete cascade, language text not null, question_text text not null, explanation text, options jsonb not null, status public.content_status not null default 'pending', unique(question_id,language));

create table public.mock_tests (id uuid primary key default gen_random_uuid(), exam_id uuid not null references public.exams(id), title text not null, test_type text not null, configuration jsonb not null, status public.content_status not null default 'draft', created_at timestamptz not null default now());
create table public.mock_test_questions (mock_test_id uuid not null references public.mock_tests(id) on delete cascade, question_id uuid not null references public.questions(id), display_order integer not null, primary key(mock_test_id,question_id));
create table public.user_attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, exam_id uuid not null references public.exams(id), mock_test_id uuid references public.mock_tests(id), started_at timestamptz not null default now(), submitted_at timestamptz, duration_seconds integer, score numeric, maximum_marks numeric, summary jsonb not null default '{}');
create table public.user_answers (id uuid primary key default gen_random_uuid(), attempt_id uuid not null references public.user_attempts(id) on delete cascade, question_id uuid not null references public.questions(id), selected_option_keys text[], numerical_answer numeric, is_correct boolean, marks_awarded numeric, time_seconds integer not null default 0, answered_at timestamptz not null default now(), unique(attempt_id,question_id));
create table public.user_topic_mastery (user_id uuid not null references auth.users(id) on delete cascade, topic_id uuid not null references public.topics(id) on delete cascade, mastery_score numeric not null default 0 check (mastery_score between 0 and 100), attempts integer not null default 0, correct integer not null default 0, updated_at timestamptz not null default now(), primary key(user_id,topic_id));
create table public.content_imports (id uuid primary key default gen_random_uuid(), exam_id uuid not null references public.exams(id), created_by uuid not null references auth.users(id), format text not null check(format in ('csv','json')), status text not null default 'validating', total_records integer not null default 0, valid_records integer not null default 0, invalid_records integer not null default 0, errors jsonb not null default '[]', created_at timestamptz not null default now());
create table public.user_roles (user_id uuid primary key references auth.users(id) on delete cascade, role text not null check(role in ('student','content_reviewer','admin')) default 'student');

create index questions_filter_idx on public.questions(exam_id,subject_id,chapter_id,topic_id,year,difficulty);
create index questions_publish_idx on public.questions(exam_id,verification_status,is_pyq);
create index attempts_user_idx on public.user_attempts(user_id,started_at desc);
create index answers_question_idx on public.user_answers(question_id);

alter table public.exam_categories enable row level security; alter table public.exams enable row level security; alter table public.exam_patterns enable row level security; alter table public.subjects enable row level security; alter table public.chapters enable row level security; alter table public.topics enable row level security; alter table public.questions enable row level security; alter table public.question_options enable row level security; alter table public.question_translations enable row level security; alter table public.mock_tests enable row level security; alter table public.mock_test_questions enable row level security; alter table public.user_attempts enable row level security; alter table public.user_answers enable row level security; alter table public.user_topic_mastery enable row level security; alter table public.content_imports enable row level security; alter table public.user_roles enable row level security;

create policy "published exams readable" on public.exams for select using (status in ('active','awaiting_verified_content'));
create policy "catalog subjects readable" on public.subjects for select using (true);
create policy "catalog chapters readable" on public.chapters for select using (status in ('verified','published'));
create policy "catalog topics readable" on public.topics for select using (status in ('verified','published'));
create policy "verified questions readable" on public.questions for select using (verification_status in ('verified','published'));
create policy "published tests readable" on public.mock_tests for select using (status='published');
create policy "own attempts" on public.user_attempts for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "own answers" on public.user_answers for all using (exists(select 1 from public.user_attempts a where a.id=attempt_id and a.user_id=auth.uid())) with check (exists(select 1 from public.user_attempts a where a.id=attempt_id and a.user_id=auth.uid()));
create policy "own mastery" on public.user_topic_mastery for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

-- Correct-answer flags are intentionally not granted to browser roles. Serve options through a protected API/view that omits is_correct.
revoke all on public.question_options from anon, authenticated;
